services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432" ##puerto en el que se estara ejecutando por defecto postgres con docker
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80" ##puerto en el que se estara ejecutando por defecto pgadmin con docker
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - postgres
